services:
  web:
    restart: unless-stopped
    environment:
      DJANGO_DEBUG: "False"

  daphne:
    restart: unless-stopped

  nginx:
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"

  celery:
    restart: unless-stopped

  celery-beat:
    restart: unless-stopped

  db:
    restart: unless-stopped

  redis:
    restart: unless-stopped
