# Generated by Django 5.2.14 on 2026-05-30 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['number'], 'verbose_name': 'Кабинка', 'verbose_name_plural': 'Кабинки'},
        ),
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='Мест'),
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='table',
            name='position_x',
            field=models.FloatField(default=0, verbose_name='Позиция X'),
        ),
        migrations.AlterField(
            model_name='table',
            name='position_y',
            field=models.FloatField(default=0, verbose_name='Позиция Y'),
        ),
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('free', 'Свободен'), ('occupied', 'Занят'), ('waiting_payment', 'Ожидает оплаты'), ('reserved', 'Зарезервирован')], default='free', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='table',
            name='type',
            field=models.CharField(choices=[('booth', 'Кабинка'), ('table', 'Стол'), ('outdoor', 'Улица')], default='table', max_length=20, verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='TableReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=200, verbose_name='Имя гостя')),
                ('guest_phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('guest_count', models.PositiveSmallIntegerField(default=2, verbose_name='Гостей')),
                ('reserved_for', models.DateTimeField(verbose_name='Дата и время')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('cancelled', 'Отменена'), ('completed', 'Гость пришёл')], default='active', max_length=20, verbose_name='Статус брони')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='table_reservations', to='accounts.employee', verbose_name='Оформил')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='tables.table', verbose_name='Кабинка')),
            ],
            options={
                'verbose_name': 'Бронь кабинки',
                'verbose_name_plural': 'Брони кабинок',
                'ordering': ['reserved_for'],
            },
        ),
    ]
