# Generated by Django 5.2.14 on 2026-06-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('web_test', 'Тест на сайте')], max_length=20)),
                ('external_user_id', models.CharField(blank=True, max_length=100)),
                ('user_message', models.TextField()),
                ('assistant_reply', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Лог диалога',
                'verbose_name_plural': 'Логи диалогов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Ассистент включён')),
                ('restaurant_name', models.CharField(default='Сакура', max_length=200, verbose_name='Название')),
                ('restaurant_address', models.TextField(blank=True, verbose_name='Адрес')),
                ('restaurant_phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('working_hours', models.TextField(default='Ежедневно 10:00–23:00', help_text='Текст для гостей, например: Пн–Вс 10:00–23:00', verbose_name='Часы работы')),
                ('about_restaurant', models.TextField(blank=True, help_text='Кухня, атмосфера, особенности', verbose_name='О ресторане')),
                ('delivery_info', models.TextField(blank=True, help_text='Условия, зона, минимальный заказ', verbose_name='Доставка')),
                ('booking_info', models.TextField(blank=True, help_text='Как забронировать стол, правила', verbose_name='Бронирование')),
                ('welcome_message', models.TextField(default='Здравствуйте! Я помощник ресторана. Спросите о меню, столах, брони или времени работы.', verbose_name='Приветствие')),
                ('ai_provider', models.CharField(choices=[('openai', 'OpenAI'), ('openrouter', 'OpenRouter'), ('custom', 'Свой API (OpenAI-совместимый)')], default='openai', max_length=20, verbose_name='Провайдер ИИ')),
                ('ai_api_key', models.CharField(blank=True, max_length=500, verbose_name='API-ключ ИИ')),
                ('ai_model', models.CharField(default='gpt-4o-mini', max_length=100, verbose_name='Модель')),
                ('ai_base_url', models.CharField(blank=True, help_text='Для OpenRouter или своего сервера', max_length=300, verbose_name='Base URL API')),
                ('extra_system_prompt', models.TextField(blank=True, verbose_name='Доп. инструкции для ИИ')),
                ('telegram_enabled', models.BooleanField(default=False, verbose_name='Telegram')),
                ('telegram_bot_token', models.CharField(blank=True, max_length=200, verbose_name='Telegram Bot Token')),
                ('whatsapp_enabled', models.BooleanField(default=False, verbose_name='WhatsApp')),
                ('whatsapp_phone_number_id', models.CharField(blank=True, max_length=50, verbose_name='WhatsApp Phone Number ID')),
                ('whatsapp_access_token', models.CharField(blank=True, max_length=500, verbose_name='WhatsApp Access Token')),
                ('whatsapp_verify_token', models.CharField(blank=True, help_text='Для подтверждения webhook в Meta', max_length=100, verbose_name='WhatsApp Verify Token')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки ассистента',
                'verbose_name_plural': 'Настройки ассистента',
            },
        ),
    ]
