# Generated by Django 5.2.14 on 2026-06-16 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_delivery_units_quantity'),
        ('tables', '0004_reservation_preorder_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('whatsapp_phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('instagram_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('preferred_channel', models.CharField(blank=True, choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram')], max_length=20)),
                ('preferred_order_type', models.CharField(blank=True, choices=[('delivery', 'Доставка'), ('takeaway', 'Самовывоз')], max_length=20)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Профиль клиента',
                'verbose_name_plural': 'Профили клиентов',
            },
        ),
        migrations.CreateModel(
            name='AIOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('erp_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_source', to='orders.order')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_orders', to='ai_assistant.clientprofile')),
            ],
            options={
                'verbose_name': 'Заказ через ассистента',
                'verbose_name_plural': 'Заказы через ассистента',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('erp_reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_source', to='tables.tablereservation')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_bookings', to='ai_assistant.clientprofile')),
            ],
            options={
                'verbose_name': 'Бронь через ассистента',
                'verbose_name_plural': 'Брони через ассистента',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('waiting_confirm', 'Ожидает подтверждения'), ('completed', 'Завершён'), ('escalated', 'Передан оператору')], default='active', max_length=20)),
                ('current_intent', models.CharField(blank=True, max_length=50)),
                ('draft_data', models.JSONField(blank=True, default=dict)),
                ('platform_message_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='ai_assistant.clientprofile')),
            ],
            options={
                'verbose_name': 'Диалог',
                'verbose_name_plural': 'Диалоги',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Клиент'), ('assistant', 'Ассистент'), ('system', 'Система')], max_length=20)),
                ('content', models.TextField()),
                ('intent_detected', models.CharField(blank=True, max_length=50)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.conversation')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['created_at'],
            },
        ),
    ]
