# Generated by Django 5.2.14 on 2026-06-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(default='Сакура', max_length=200, verbose_name='Название')),
                ('restaurant_address', models.TextField(blank=True, verbose_name='Адрес')),
                ('restaurant_phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('working_hours', models.TextField(default='Ежедневно 10:00–23:00', verbose_name='Часы работы')),
                ('about_restaurant', models.TextField(blank=True, help_text='Кухня, атмосфера', verbose_name='О ресторане')),
                ('delivery_info', models.TextField(blank=True, verbose_name='Доставка')),
                ('booking_info', models.TextField(blank=True, verbose_name='Бронирование')),
                ('promotions', models.TextField(blank=True, verbose_name='Акции')),
                ('welcome_message', models.TextField(default='Здравствуйте! 🍵 Я помощник чайханы «Сакура».\nМогу принять заказ, забронировать стол или ответить на вопросы о меню.\n\nКоманды:\n/order — заказ\n/booking — бронь\n/history — ваши заказы\n/help — помощь', verbose_name='Приветствие (/start)')),
                ('custom_system_prompt', models.TextField(default='Дополнительные правила (можно изменить в настройках ERP):\n\n- Всегда представляйся как помощник чайханы «Сакура»\n- При первом обращении — тёплое приветствие\n- Если клиент злится — предложи позвонить в ресторан', help_text='Добавляются к базовому промпту. Правила безопасности и JSON-формат зафиксированы в коде.', verbose_name='Доп. инструкции для ИИ')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Ассистент включён')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки ассистента',
                'verbose_name_plural': 'Настройки ассистента',
            },
        ),
    ]
